### ISSUE TITLE
Getting table column information in addition to the table_name

### ISSUE THREAD

**Issue by kivilahtio** [karupanerura/MySQL-Dump-Parser-XS#1]
Hi!

We are using this module to parse the mysqldump output, but because this module returns a
%hash of ->{$columnName} = $columnValues;
there is no way of putting it back together in the correct order.
What we would need is a subroutine to get the following information for each of the table's columns:
- column index (first, second, third, ...)
- column data type
- column maximum size (what is inside parenthesis, eg. "varchar (70)" => maxSize = 70

**Comment by karupanerura** [comment]
Hi. Thank you for your report.
I suggest using [DBIx::Inspector](https://metacpan.org/pod/DBIx::Inspector) to solve the problem.

**Comment by kivilahtio** [comment]
Hi! Thanks for the tip.
